				$(".homes").click(function(){
					location.href="index_login.html";
				});
				$(".put").click(function(){
					location.href="order_list.html";
				});
				$(".order").click(function(){
					location.href="lists.html";
				});
				$(".before").click(function(){
					window.history.go(-1);
				});
				$(".addAddress").click(function(){
					location.href="information.html";
				});
